name: tpfinal
networks:
  intranet:
    name: intranet
    driver: bridge
services:
  client1:
    container_name: client1
    depends_on:
      - server
    image: clientbn:latest
    networks:
      - intranet
    volumes:
      - ./client/client.js:/usr/src/app/client.js
  server:
    container_name: server
    image: serverbn:latest
    networks:
      - intranet
    ports:
      - 3000:3000
    volumes:
      - ./server/server.js:/usr/src/app/server.js
