name: tpfinal
networks:
  intranet:
    name: intranet
    driver: bridge
services:
  client1:
    container_name: client1
    depends_on:
      - server
    image: clientbn:latest
    networks:
      - intranet
    volumes:
      - ./client/client.js:/usr/src/app/client.js
      - ./client/commands.js:/usr/src/app/commands.js
  client2:
    container_name: client2
    depends_on:
      - server
    image: clientbn:latest
    networks:
      - intranet
    volumes:
      - ./client/client.js:/usr/src/app/client.js
      - ./client/commands.js:/usr/src/app/commands.js
  server:
    container_name: server
    image: serverbn:latest
    environment:
      - DOWNLOAD_FILEPATH=./downloads
    networks:
      - intranet
    ports:
      - 3000:3000
    volumes:
      - ./server/server.js:/usr/src/app/server.js
      - ./server/results_handlers.js:/usr/src/app/results_handlers.js
      - ./server/setup.js:/usr/src/app/setup.js
